# Generated by Django 4.2 on 2023-07-31 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('tour', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('pax', models.IntegerField()),
                ('time', models.TimeField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
