# Generated by Django 4.2 on 2023-07-31 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightsonbikes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reservations',
            new_name='Reservation',
        ),
    ]
